In [1]:
import numpy as np

arr=np.array([1,2,31,90]) # array creation
print(arr,type(arr))

[ 1  2 31 90] <class 'numpy.ndarray'>


In [2]:
arr=np.array([1,20,7,39])
print(arr)

[ 1 20  7 39]


In [3]:
arr[1]=5.6
print(arr)

[ 1  5  7 39]


Difference between List and array


In [4]:
l=list[1,2.3,True]
print(l)

list[1, 2.3, True]


In [5]:
arr=np.array([1,2,4,5.6,'Nice'])
print(arr,type(arr))

['1' '2' '4' '5.6' 'Nice'] <class 'numpy.ndarray'>


In [6]:
arr=[1,2,4,5.6,'Nice']
print(arr,type(arr))

[1, 2, 4, 5.6, 'Nice'] <class 'list'>


In [7]:
arr=np.array([10,20,45])*5
print(arr)

[ 50 100 225]


In [8]:
arr=[10,20,45]*5
print(arr)

[10, 20, 45, 10, 20, 45, 10, 20, 45, 10, 20, 45, 10, 20, 45]


2 dimension list and array

In [9]:
l=[[1,2],[35,10]]
print(l)

[[1, 2], [35, 10]]


To create 2d array

In [10]:
arr=np.array([1,2,3,100,45,7,6],ndmin=2)
print(arr)

[[  1   2   3 100  45   7   6]]


It should have same length or columns in every rows

In [11]:
arr=np.array([[1,2,3],[100,45,7,6]],ndmin=2)
print(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
arr=np.array([[1,2,3],[100,45,7]],ndmin=2)
print(arr)

[[  1   2   3]
 [100  45   7]]


To get about the dimension,

how much dimension is the array is.

It should have column values must be same. in 2 D dimension arrays

In [ ]:
arr.ndim

2

to get count of rows and columns

In [ ]:
arr.shape

(2, 3)

arange

works as range methos.
end value excluded.
floating values canot be given as step


In [ ]:
#arange()
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


in list it cannot accept float values

In [ ]:
arr=list(range(1,10,2.5))
print(arr)

TypeError: 'float' object cannot be interpreted as an integer

in array it can accept float values

In [ ]:
arr=np.arange(1,10,2.5)
print(arr)

[1.  3.5 6.  8.5]


linspace()
support for 50 index

It gives float values

In [ ]:
#linspace()

arr=np.linspace(1,10)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

3 acts like it should give 3 values

In [ ]:
arr=np.linspace(1,10,3)
arr

array([ 1. ,  5.5, 10. ])

divides with equally distributed values, with how much values to be printed using num of value given. 

end is inclusive

In [ ]:
arr=np.linspace(1,10,4)
arr

array([ 1.,  4.,  7., 10.])

2d array with 5 rows and 2 columns

In [ ]:
arr=np.array([[1,2,1],[3,4,2],[5,6,3],[7,8,4],[9,10,5]])
print(arr)

[[ 1  2  1]
 [ 3  4  2]
 [ 5  6  3]
 [ 7  8  4]
 [ 9 10  5]]


In [ ]:
#indexing and slicing

arr[0]

array([1, 2, 1])

In [ ]:
arr[-1]

array([ 9, 10,  5])

In [ ]:
arr[1,0]

np.int64(3)

In [ ]:
arr[[1,3]]

array([[3, 4, 2],
       [7, 8, 4]])

In [ ]:
arr[0]=[7,3,5]
arr

array([[ 7,  3,  5],
       [ 3,  4,  2],
       [ 5,  6,  3],
       [ 7,  8,  4],
       [ 9, 10,  5]])

In [ ]:
arr[[0],[2]]

array([5])

In [ ]:
arr[2:4,1:3]

array([[6, 3],
       [8, 4]])

In [ ]:
arr[0:2,-1:-3:-1]

array([[5, 3],
       [2, 4]])

In [ ]:
arr[0:3:2,0:2]

array([[7, 3],
       [5, 6]])

In [ ]:
arr=np.array([[1,11,44],[2,12,55],[3,22,66],[4,33,77]])
arr

array([[ 1, 11, 44],
       [ 2, 12, 55],
       [ 3, 22, 66],
       [ 4, 33, 77]])

In [ ]:
arr[0:2,2:0:-1]

array([[44, 11],
       [55, 12]])

In [ ]:
arr[1::-1,1:3]

array([[12, 55],
       [11, 44]])

Random 
it is a module.
it has Rand() - used to generate random numbers

rand = returns float

In [ ]:
#random

np.random.rand()

0.4604217466517764

Randint - It gives the integer as a random number.

it gives the random num between the given range

In [ ]:
#Randint()

np.random.randint(1,20)

10

Small game using randint

In [ ]:
import numpy as np

n=np.random.randint(1,100)
count=0
while True:
    user=int(input("Enter a guessed number"))
    count+=1 
    if user==n:
        print("You have entered correct random number")
        break
    elif user<n:
        print("Random number is greater than what you entered")
    elif user>n:
        print("Random number is less than what you entered")
print(count)

Random number is less than what you entered
Random number is greater than what you entered
Random number is greater than what you entered
Random number is less than what you entered
Random number is less than what you entered
Random number is less than what you entered
You have entered correct random number
7


In [ ]:
l=['red','blue','green']

np.random.choice(l)

np.str_('blue')

In [12]:
choice=['stone','paper','scissor']
u_count=0
n_count=0
for i in range(1,4):
    n=np.random.choice(choice)
    print(f"Computer Choice: {n}")
    user=input("Enter your choice : ")
    print(f"User Choice: {user}")
    if user==n:
        pass
    elif (user=='stone' and n=='paper') or (user=='paper' and n=='scissor') or (user=='scissor' and n=='stone'):
        n_count+=1
    else:
        u_count+=1

print(n_count)
print(u_count)

if n_count > u_count:
    print("computer won the game")
elif n_count==u_count:
    print("Both are tie")
else:
    print("User won the game")    

Computer Choice: stone
User Choice: paper
Computer Choice: stone
User Choice: stone
Computer Choice: paper
User Choice: scissor
0
2
User won the game


to generate more than 1 random number

Start, stop, size

In [ ]:
np.random.randint(1,100,5)

array([64, 90, 30, 48, 77], dtype=int32)

To generate arrays

rows and columns (2,5)

In [ ]:
np.random.randint(1,100,(2,5))

array([[10, 94, 56, 31, 46],
       [56, 72, 37, 67, 70]], dtype=int32)

Aggregation Function

In [ ]:
arr=np.random.randint(1,100,(2,5))
arr

array([[ 3, 62, 55, 86, 68],
       [59, 88, 95, 34, 94]], dtype=int32)

In [ ]:
np.sum(arr)

np.int64(644)

In [ ]:
np.sum(arr,axis=1)

array([274, 370])

In [ ]:
np.sum(arr,axis=0)

array([ 62, 150, 150, 120, 162])

To select the simgle colum or row, do slicing. 

Here 3rd column sum we are doing using slicing

In [ ]:
np.sum(arr[:,2],axis=0)

np.int64(150)

In [ ]:
np.min(arr)

np.int32(3)

In [ ]:
np.max(arr,axis=1)

array([86, 95], dtype=int32)

In [ ]:
np.mean(arr)

np.float64(64.4)

Seed= used handle randomness. it will fix the values

we can give any number in the arguments

In [ ]:
np.random.seed(42)
np.random.randint(1,100,(2,5))

array([[52, 93, 15, 72, 61],
       [21, 83, 87, 75, 75]], dtype=int32)

In [ ]:
np.random.seed(2)
np.random.randint(1,100,(2,5))

array([[41, 16, 73, 23, 44],
       [83, 76,  8, 35, 50]], dtype=int32)

In [ ]:
np.random.seed(100)
np.random.randint(1,100,(2,5))

array([[ 9, 25, 68, 88, 80],
       [49, 11, 95, 53, 99]], dtype=int32)

Unique = It returns unique values

In [ ]:
# unique

np.unique(arr)

array([ 3, 34, 55, 59, 62, 68, 86, 88, 94, 95], dtype=int32)

In [ ]:
arr=np.array([1,2,3,1,1,2,3])
np.unique(arr,return_counts=False)

array([1, 2, 3])

return counts

It returns tuple. with 2 vlaues. 

1 is unique values and 2nd is count of the unique values

In [ ]:
arr=np.array([1,2,3,1,1,2,3])
np.unique(arr,return_counts=True)

(array([1, 2, 3]), array([3, 2, 2]))

In [ ]:
arr=np.array([3,5,3,5,1,2,5,3,4,4,4])
unique_val, unique_counts=np.unique(arr,return_counts=True)
max=np.max(unique_counts)
mode=unique_val[unique_counts==max]
mode


array([3, 4, 5])

In [37]:
#expected outpu [1,2,4,5]

l=[[1,2],[4,5],10]

new=[]
for val in l:
    if (type(val))==list:
        l1=[i for i in val]
        new = new + l1
    else:
        new.append(val)
print(new)

[[1, 2], [4, 5], 10]


In [41]:
arr=np.array([1,2],[3,1],[1,2],ndmin=3)
print(arr)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [38]:
arr

array([[  1,   2,   3, 100,  45,   7,   6]])

In [ ]:
arr.flatten() # to convert 2d to 1d
#flatten method returns new array

In [39]:
arr

array([[  1,   2,   3, 100,  45,   7,   6]])

In [42]:
#reshape()
#arr 3x2
#arr.reshape(row,col)
#arr.reshape(10,2)  #Value Error: Cannot reshape array of size 6 into hape (10,2)

arr.reshape(1,6)

array([[1, 2, 3, 1, 1, 2]])

In [43]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [1],
       [1],
       [2]])

In [ ]:
# to convert 2D to 1D
# also to change the shape
arr.reshape(-1)

array([1, 2, 3, 1, 1, 2])

In [ ]:
arr.resize()

In [ ]:
#Variance of X

x=np.array([10,20,30,40,50])
y=np.array([100,200,300,400,500])

mean_x=np.mean(x)
n=0
for i in x:
    sum=0
    n+=1
    b=(i-mean_x)
    sum+=b
    sum_2=sum**2
var_x=sum_2/n

var_x


np.float64(80.0)

Variance of x

In [52]:
var_x=np.sum((x-np.mean(x))**2)/n
var_x

np.float64(200.0)

Variance of Y

In [53]:
var_y=np.sum((y-np.mean(y))**2)/n
var_y

np.float64(20000.0)

Covariance of (X,Y)

In [54]:
Cov_XY=np.sum((x-np.mean(x))*(y-np.mean(y)))/n
Cov_XY

np.float64(2000.0)